version: '3.8'

services:
  db:
    image: postgres:16.8-alpine3.20
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: trackmyspend
      POSTGRES_USER: jerem
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: trackmyspend-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trackmyspend
      SPRING_DATASOURCE_USERNAME: jerem
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  pg_data:
