version: '3.8'

services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: trackmyspend
      POSTGRES_USER: jerem
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "jerem"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  app:
    build: .
    container_name: trackmyspend-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trackmyspend
      SPRING_DATASOURCE_USERNAME: jerem
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-update
    ports:
      - "8080:8080"

volumes:
  pg_data:
